# Generated by Django 3.1.5 on 2021-09-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('konten', models.CharField(max_length=1000)),
            ],
        ),
    ]
