# Generated by Django 3.1.5 on 2021-09-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='artikel',
            old_name='genre',
            new_name='deskripsi',
        ),
        migrations.AddField(
            model_name='artikel',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='readicapp.genre'),
        ),
    ]
