# Generated by Django 3.2.8 on 2021-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readicapp', '0007_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='cover',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sex',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
